# Generated by Django 2.1.3 on 2018-11-24 23:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('community_unit', models.CharField(max_length=50, null=True)),
                ('school_id', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('olevel_students', models.CharField(max_length=50, null=True)),
                ('alevel_students', models.CharField(max_length=50, null=True)),
                ('boarding_students', models.CharField(max_length=50, null=True)),
                ('day_students', models.CharField(max_length=50, null=True)),
                ('boarding_fee_S3', models.CharField(max_length=50, null=True)),
                ('day_fee_S3', models.CharField(max_length=50, null=True)),
                ('boarding_fee_S5', models.CharField(max_length=50, null=True)),
                ('day_fee_S5', models.CharField(max_length=50, null=True)),
                ('female_students', models.CharField(max_length=50, null=True)),
                ('male_students', models.CharField(max_length=50, null=True)),
                ('number_of_students', models.CharField(max_length=50, null=True)),
                ('number_of_teachers', models.IntegerField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('date_school_enrolled', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
